name: Deploy Backend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Backend Repo
        uses: actions/checkout@v2
        with:
          repository: mugiaadha/app-pkm
          token: ${{ secrets.VPS_PAT_TOKEN }}
          path: backend

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Download cabang-config.json from Supabase
        run: |
          curl -o cabang-config.json https://wulzrugvpldjbdsxscku.supabase.co/storage/v1/object/public/app-pkm/cabang-config.json

      - name: Deploy Backend to VPS
        run: |
          VPS_IP="${{ secrets.VPS_HOST }}"

          ACTIVE_SUBDOMAINS=$(jq -r '.[] | select(.active == true) | .subdomain' ../cabang-config.json)

          for SUBDOMAIN in $ACTIVE_SUBDOMAINS; do
            echo "Deploy ke $SUBDOMAIN"
            ssh root@$VPS_IP "mkdir -p /var/www/html/$SUBDOMAIN/backend/"
            scp -r ./* root@$VPS_IP:/var/www/html/$SUBDOMAIN/backend/
          done
        working-directory: backend
