name: Deploy to VPS

on:
  push:
    branches:
      - main # Ganti sesuai branch yang kamu pakai

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 103.84.207.50 >> ~/.ssh/known_hosts

      - name: Install dependencies & Build
        run: |
          npm install
          npm run build
        working-directory: . # Ganti dengan folder subproject jika ada

      - name: Download .github/workflows/cabang-config.json from JSONBin
        run: |
          curl -s https://api.jsonbin.io/v3/b/68074a498a456b79668eac81 -o .github/workflows/cabang-config.json

      - name: Bersihkan Folder di VPS dan Deploy
        run: |
          VPS_IP="103.84.207.50"

          echo "Hapus semua folder di /var/www/html"
          ssh root@$VPS_IP 'rm -rf /var/www/html/*'

          echo "Buat folder dan deploy ke setiap cabang"
          for SUBDOMAIN in $(jq -r '.[] | .subdomain' .github/workflows/cabang-config.json); do
            ACTIVE=$(jq -r ".[] | select(.subdomain == \"$SUBDOMAIN\") | .active" .github/workflows/cabang-config.json)
            
            if [ "$ACTIVE" == "true" ]; then
              echo "Deploy ke $SUBDOMAIN"
              ssh root@$VPS_IP "mkdir -p /var/www/html/$SUBDOMAIN"
              scp -r ./dist/app-pkm/browser/* root@$VPS_IP:/var/www/html/$SUBDOMAIN/
            else
              echo "Set non-aktif page untuk $SUBDOMAIN"
              ssh root@$VPS_IP "mkdir -p /var/www/html/$SUBDOMAIN"
              scp inactive.html root@$VPS_IP:/var/www/html/$SUBDOMAIN/index.html
            fi
          done
