name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Checkout Frontend Repo
        uses: actions/checkout@v2
        with:
          repository: mugiaadha/app-pkm
          token: ${{ secrets.VPS_PAT_TOKEN }}
          path: frontend

      - name: Install dependencies & Build
        run: |
          npm install
          npm run build
        working-directory: frontend

      - name: Download cabang-config.json from Supabase
        run: |
          curl -o cabang-config.json https://wulzrugvpldjbdsxscku.supabase.co/storage/v1/object/public/app-pkm/cabang-config.json

      - name: Deploy Frontend to VPS
        run: |
          VPS_IP="${{ secrets.VPS_HOST }}"

          ACTIVE_SUBDOMAINS=$(jq -r '.[] | select(.active == true) | .subdomain' ../cabang-config.json)
          INACTIVE_SUBDOMAINS=$(jq -r '.[] | select(.active == false) | .subdomain' ../cabang-config.json)

          for SUBDOMAIN in $ACTIVE_SUBDOMAINS; do
            echo "Deploy ke $SUBDOMAIN"

            fe_path="/var/www/html/$SUBDOMAIN"

            ssh root@$VPS_IP "mkdir -p $fe_path"
            rsync -avz -e "ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=5" --delete --exclude='.git' dist/app-pkm/browser/ root@$VPS_IP:$fe_path/ --log-file=rsync_log.txt
          done

          for SUBDOMAIN in $INACTIVE_SUBDOMAINS; do
            echo "Set non-aktif page untuk $SUBDOMAIN"

            fe_path="/var/www/html/$SUBDOMAIN"

            ssh root@$VPS_IP "mkdir -p $fe_path"
            rsync -avz -e "ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=5" --delete --exclude='.git' ./inactive.html root@$VPS_IP:$fe_path/index.html --log-file=rsync_log.txt
          done
        working-directory: frontend

  deploy-backend:
    needs: deploy-frontend
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Download cabang-config.json from Supabase
        run: |
          curl -o cabang-config.json https://wulzrugvpldjbdsxscku.supabase.co/storage/v1/object/public/app-pkm/cabang-config.json

      - name: Deploy Backend to VPS
        run: |
          VPS_IP="${{ secrets.VPS_HOST }}"

          ACTIVE_SUBDOMAINS=$(jq -r '.[] | select(.active == true) | .subdomain' ../cabang-config.json)

          for SUBDOMAIN in $ACTIVE_SUBDOMAINS; do
            echo "Deploy ke $SUBDOMAIN"

            be_path="/var/www/html/$SUBDOMAIN/backend"

            # Buat folder kalau belum ada
            ssh root@$VPS_IP "mkdir -p $be_path"

            # Clone repository langsung ke VPS
            ssh root@$VPS_IP "git clone git@github.com:mugiaadha/app-pkm-clenic.git $be_path"

            # Menjalankan setup atau perintah lain yang diperlukan setelah clone (misal: install dependencies)
            ssh root@$VPS_IP "cd $be_path && git pull origin main && npm install" # Sesuaikan dengan perintah setup BE

          done

  # deploy-backend:
  #   needs: deploy-frontend
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Setup SSH
  #       run: |
  #         mkdir -p ~/.ssh
  #         echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
  #         chmod 600 ~/.ssh/id_rsa
  #         ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

  #     - name: Checkout Backend Repo
  #       uses: actions/checkout@v2
  #       with:
  #         repository: mugiaadha/app-pkm-clenic
  #         token: ${{ secrets.VPS_PAT_TOKEN }}
  #         path: backend

  #     - name: Download cabang-config.json from Supabase
  #       run: |
  #         curl -o cabang-config.json https://wulzrugvpldjbdsxscku.supabase.co/storage/v1/object/public/app-pkm/cabang-config.json

  #     - name: Deploy Backend to VPS
  #       run: |
  #         VPS_IP="${{ secrets.VPS_HOST }}"

  #         ACTIVE_SUBDOMAINS=$(jq -r '.[] | select(.active == true) | .subdomain' ../cabang-config.json)

  #         for SUBDOMAIN in $ACTIVE_SUBDOMAINS; do
  #           echo "Deploy ke $SUBDOMAIN"

  #           be_path="/var/www/html/$SUBDOMAIN/backend"

  #           # Buat folder kalau belum ada
  #           ssh root@$VPS_IP "mkdir -p $be_path"

  #           # Kirim file menggunakan rsync
  #           rsync -avz -e "ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=5" --delete --exclude='.git' ./ root@$VPS_IP:$be_path/ --log-file=rsync_log.txt
  #         done
  #       working-directory: backend
