name: Deploy to VPS

on:
  push:
    branches:
      - main # Ganti sesuai branch yang kamu pakai

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 103.84.207.50 >> ~/.ssh/known_hosts

      - name: Install dependencies & Build
        run: |
          npm install
          npm run build
        working-directory: . # Ganti dengan folder subproject jika ada

      - name: Bersihkan dan Buat Ulang Folder di VPS
        run: |
          VPS_IP="103.84.207.50"

          echo "Hapus semua folder di /var/www/html"
          ssh root@$VPS_IP 'rm -rf /var/www/html/*'

          echo "Buat folder untuk tiap cabang"
          for SUBDOMAIN in $(jq -r '.[].subdomain' .github/workflows/cabang-config.json); do
            ssh root@$VPS_IP "mkdir -p /var/www/html/$SUBDOMAIN"
          done

      - name: Deploy hasil build ke cabang aktif
        run: |
          VPS_IP="103.84.207.50"
          for SUBDOMAIN in $(jq -r '.[] | select(.active == true) | .subdomain' .github/workflows/cabang-config.json); do
            echo "Deploy ke $SUBDOMAIN"
            ssh root@$VPS_IP "mkdir -p /var/www/html/$SUBDOMAIN"
            scp -r ./dist/app-pkm/browser/* root@$VPS_IP:/var/www/html/$SUBDOMAIN/
          done

      - name: Deploy halaman non-aktif ke cabang yang belum bayar
        run: |
          VPS_IP="103.84.207.50"
          for SUBDOMAIN in $(jq -r '.[] | select(.active == false) | .subdomain' .github/workflows/cabang-config.json); do
            echo "Set non-aktif page untuk $SUBDOMAIN"
            ssh root@$VPS_IP "mkdir -p /var/www/html/$SUBDOMAIN"
            scp inactive.html root@$VPS_IP:/var/www/html/$SUBDOMAIN/index.html
          done