name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Checkout Frontend Repo
        uses: actions/checkout@v2
        with:
          repository: mugiaadha/app-pkm
          token: ${{ secrets.VPS_PAT_TOKEN }}
          path: frontend

      - name: Install dependencies & Build
        run: |
          npm install
          npm run build
        working-directory: frontend

      - name: Download cabang-config.json from Supabase
        run: |
          curl -o cabang-config.json https://wulzrugvpldjbdsxscku.supabase.co/storage/v1/object/public/app-pkm/cabang-config.json

      - name: Deploy Frontend to VPS
        run: |
          VPS_IP="${{ secrets.VPS_HOST }}"

          echo "Hapus semua folder di /var/www/html"
          ssh root@$VPS_IP 'rm -rf /var/www/html/*'

          ACTIVE_SUBDOMAINS=$(jq -r '.[] | select(.active == true) | .subdomain' ../cabang-config.json)
          INACTIVE_SUBDOMAINS=$(jq -r '.[] | select(.active == false) | .subdomain' ../cabang-config.json)

          echo "Kompresi hasil build..."
          cd dist/app-pkm/browser
          tar czf ../../frontend.tar.gz ./*
          cd -

          for SUBDOMAIN in $ACTIVE_SUBDOMAINS; do
            echo "Deploy ke $SUBDOMAIN"

            fe_path="/var/www/html/$SUBDOMAIN"

            ssh root@$VPS_IP "mkdir -p $fe_path"
            rsync -avz dist/app-pkm/browser/ root@$VPS_IP:$fe_path/
          done

          for SUBDOMAIN in $INACTIVE_SUBDOMAINS; do
            echo "Set non-aktif page untuk $SUBDOMAIN"
            ssh root@$VPS_IP "mkdir -p $fe_path"
            rsync -avz ./inactive.html root@$VPS_IP:$fe_path/index.html
          done
        working-directory: frontend
