name: Deploy FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [tabaro.clenicapp.com/test-auto]  # isi folder yang mau di-deploy

    steps:
      - uses: actions/checkout@v3

      - name: FTP Deploy to ${{ matrix.folder }}
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 103.93.56.225:2110
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build
          server-dir: ./${{ matrix.folder }}