name: CI/CD to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone Private Repo ke VPS Folder Lokal
        run: |
          git clone git@github.com:mugiaadha/app-pkm.git

      # Contoh step deploy ke VPS kalau butuh:
      - name: Deploy ke VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@103.84.207.50 'echo "Deploy script di sini"'
