name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug DEPLOY_KEY
      run: |
        echo "Checking if DEPLOY_KEY is set"
        if [ -z "${{ secrets.DEPLOY_KEY }}" ]; then
          echo "DEPLOY_KEY is not set"
        else
          echo "DEPLOY_KEY is set"
        fi

    - name: Setup SSH key for VPS
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy-key
        chmod 600 ~/.ssh/deploy-key
        ssh-keyscan 103.84.207.50 >> ~/.ssh/known_hosts  # Ganti dengan IP VPS kamu

    - name: SSH into VPS and deploy
      run: |
        ssh -i ~/.ssh/deploy-key root@103.84.207.50 "cd /var/www/html && ls && # Langkah deployment lainnya"
